//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvoVI.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvoVI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [ EM | EL ]	[ NULL ]	[ KEYBOARD ]	TURN_RIGHT
        ///[ EM | EL ]	[ NULL ]	[ KEYBOARD ]	TURN_LEFT
        ///[ EM | EL ]	[ NULL ]	[ KEYBOARD ]	PITCH_DOWN
        ///[ EM | EL ]	[ NULL ]	[ KEYBOARD ]	PITCH_UP
        ///[ EM | EL ]	[ NULL ]	[ KEYBOARD ]	ROLL_RIGHT
        ///[ EM | EL ]	[ NULL ]	[ KEYBOARD ]	ROLL_LEFT
        ///[ EM | EL ]	[ NULL ]	[ KEYBOARD ]	STRAFE_RIGHT
        ///[ EM | EL ]	[ NULL ]	[ KEYBOARD ]	STRAFE_LEFT
        ///[ EM | EL ]	[ NULL ]	[ KEYBOARD ]	AFTERBURNER
        ///[ EM | EL ]	[ NULL ]	[ KEYBOARD ]	INERTIAL_SYSTEM_ON_OFF
        ///[ EM | EL ]	[ NULL ]	[ KEYBOARD ]	MATCH_ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Keymap8_Layout {
            get {
                return ResourceManager.GetString("Keymap8_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [EM | EL]	[ PlayerData ]			&lt;string&gt;	Pilot Name 							(string)
        ///[EM | EL]	[ PlayerShipData ]		&lt;integer&gt;	Fuel 								(integer)
        ///[EM | EL]	[ PlayerData ]			&lt;string&gt;	Cash 								(string, includes commas)
        ///[EM | EL]	[ PlayerShipData ]		&lt;string&gt;	Cargo Bay 1 						(string, cargo type and number, or will display &apos;Empty&apos; if nothing)
        ///[EM | EL]	[ PlayerShipData ]		&lt;string&gt;	Cargo Bay 2
        ///[EM | EL]	[ PlayerShipData ]		&lt;string&gt;	Cargo Bay 3
        ///[EM | EL]	[ PlayerShipData ]		&lt;string&gt;	Cargo Bay 4
        ///[EM | EL]	[ PlayerShipData [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Savedata_Layout {
            get {
                return ResourceManager.GetString("Savedata_Layout", resourceCulture);
            }
        }
    }
}
