//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacVI.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VacVI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;style&gt;
        ///		div.player,
        ///		div.vi,
        ///		div.command
        ///		{
        ///			color: #333;
        ///			margin: 10px;
        ///			padding: 10px;
        ///			border: 2px solid;
        ///			/* border-radius: 5px; */
        ///			border: 2px solid #888;
        ///			font-family: consolas;
        ///		}
        ///
        ///		div.player,
        ///		div.player div
        ///		{
        ///			border-color: #ffe599 !important;
        ///		}
        ///
        ///		div.player
        ///		{
        ///			background-color: #fff2cc;
        ///		}
        ///
        ///		div.vi,
        ///		div.vi div
        ///		{
        ///			border-color: #bdd6ee !important;
        ///		}
        ///
        ///		div.vi
        ///		{
        ///			background-color: #deeaf6;
        ///		}
        ///
        ///		d [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string DialogTreeHTML_Template {
            get {
                return ResourceManager.GetString("DialogTreeHTML_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ################################################################
        ///##                                                            ##
        ///## !!! THIS FILE IS BEING USED BY THE PROGRAM !!!             ##
        ///## DO NOT EDIT THIS FILE, UNLESS YOU KNOW WHAT YOU ARE DOING! ##
        ///##                                                            ##
        ///################################################################
        ///
        ///[ EMERC | ELGCY ]	[ NULL ]	[ KEYBOARD ]	TURN_RIGHT																	&apos;Turn Right&apos;
        ///[ EMERC | ELGCY ]	[ NULL ]	[ KEYB [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Keymap8_Layout {
            get {
                return ResourceManager.GetString("Keymap8_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ################################################################
        ///##                                                            ##
        ///## !!! THIS FILE IS BEING USED BY THE PROGRAM !!!             ##
        ///## DO NOT EDIT THIS FILE, UNLESS YOU KNOW WHAT YOU ARE DOING! ##
        ///##                                                            ##
        ///################################################################
        ///
        ///[ EMERC | ELGCY ]		[ PlayerData ]			&lt;string&gt;	Pilot Name 							(string)
        ///[ EMERC | ELGCY ]		[ PlayerShipData ]		&lt;s [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Savedata_Layout {
            get {
                return ResourceManager.GetString("Savedata_Layout", resourceCulture);
            }
        }
    }
}
